name: Testing onmergerequest event

on: 
  pull_request:
    types: [closed]
  push:

jobs: 
  container-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: ls -al
    - name: bulding Dockerfile
      run: docker build .